// File scope: v3.6.0 EC-8-2 FAQ + product Q&A responder.
//
// Pipeline (HARD GATE: complex_fn must NOT increase from 4):
//
//	Respond
//	  -> guardRespond            (cyclomatic 3)
//	  -> retrieveCandidates      (cyclomatic 4)
//	  -> rerank (top-3)          (cyclomatic 3)
//	  -> phraseReply (LLM second)(cyclomatic 4)
//	  -> routeByConfidence       (cyclomatic 4)
//
// Auto-reply gate (per plan EC-8-2 acceptance):
//   - confidence > 0.8 AND review-flag clear -> auto_replied
//   - 0.6 <= confidence <= 0.8                  -> suggested
//   - confidence < 0.6 OR review-flag set       -> escalated
//
// Reuse evidence:
//   - LLM failover pattern: v3.2.0 EC-2-1 description_gen +
//     v3.4.0 EC-5-1 video_script.go.
//   - port.AITextGenerator (v3.2.0).
//   - Closer + sync.Mutex guard pattern: v3.4.0 EC-5-1 video_script.go.
package customerservice

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/nfsarch33/helixon-ec/internal/port"
)

// MaxFAQResponseLength caps the auto-generated reply length. The
// platform reply surfaces (TikTok message reply, FB Messenger Send
// API) cap at 1000 chars; the responder uses 500 as a conservative
// budget and rejects over-budget LLM output (typed
// ErrFAQResponseTooLong).
const MaxFAQResponseLength = 500

// FAQOutcome enumerates the three auto-reply gate destinations.
type FAQOutcome string

const (
	FAQOutcomeAutoReplied FAQOutcome = "auto_replied"
	FAQOutcomeSuggested   FAQOutcome = "suggested"
	FAQOutcomeEscalated   FAQOutcome = "escalated"
	FAQOutcomeNoMatch     FAQOutcome = "no_match"
)

// FAQPhraseSource captures whether the reply text was generated by
// the LLM rephrase pass or pulled verbatim from the matched FAQ
// answer (the deterministic template fallback).
type FAQPhraseSource string

const (
	FAQPhraseSourceLLM      FAQPhraseSource = "llm"
	FAQPhraseSourceTemplate FAQPhraseSource = "template"
)

// FAQEntry is one row in the faq_entries table (migration 0015).
type FAQEntry struct {
	TenantID       string
	EntryID        string
	Language       Language
	IntentCategory Intent
	Question       string
	Answer         string
	Keywords       []string
}

// FAQSearchQuery is the small port the responder uses to consult
// the FAQ store.
type FAQSearchQuery struct {
	TenantID string
	Language Language
	Intent   Intent
}

// FAQStore is implemented by the Postgres adapter (production) +
// the in-memory test double.
type FAQStore interface {
	Search(ctx context.Context, query FAQSearchQuery) ([]FAQEntry, error)
}

// FAQRequest is the unit of work submitted to Respond.
type FAQRequest struct {
	MessageID      string
	TenantID       string
	Channel        string
	Text           string
	Classification EnquiryResult
}

// FAQResult is the structured Respond output.
type FAQResult struct {
	MessageID      string
	Outcome        FAQOutcome
	ReplyText      string
	MatchedEntryID string
	Confidence     float64
	PhraseSource   FAQPhraseSource
	MatchError     error // typed sentinel surfaced when no FAQ matched
	RespondedAt    time.Time
}

// FAQResponderMetrics is the small port the responder emits
// counters through.
type FAQResponderMetrics interface {
	RecordFAQResponse(tenantID, outcome string)
}

// FAQResponderConfig wires the agent.
type FAQResponderConfig struct {
	Generator           port.AITextGenerator
	Store               FAQStore
	TenantID            string
	AutoReplyConfidence float64
	SuggestConfidence   float64
	Now                 func() time.Time
	Metrics             FAQResponderMetrics
}

// FAQResponder is the EC-8-2 agent.
type FAQResponder struct {
	generator      port.AITextGenerator
	store          FAQStore
	tenantID       string
	autoReplyFloor float64
	suggestFloor   float64
	now            func() time.Time
	logger         *slog.Logger
	metrics        FAQResponderMetrics

	mu     sync.Mutex
	closed bool
}

// NewFAQResponder constructs the agent. Defaults: auto-reply at
// 0.8, suggest at 0.6 (per plan EC-8-2 acceptance).
func NewFAQResponder(logger *slog.Logger, cfg FAQResponderConfig) (*FAQResponder, error) {
	if logger == nil {
		logger = slog.Default()
	}
	if cfg.Generator == nil {
		return nil, fmt.Errorf("%w: port.AITextGenerator required", ErrFAQResponderUnconfigured)
	}
	if cfg.Store == nil {
		return nil, fmt.Errorf("%w: FAQStore required", ErrFAQResponderUnconfigured)
	}
	if strings.TrimSpace(cfg.TenantID) == "" {
		return nil, fmt.Errorf("%w: TenantID required", ErrFAQResponderUnconfigured)
	}
	if cfg.AutoReplyConfidence <= 0 {
		cfg.AutoReplyConfidence = 0.8
	}
	if cfg.SuggestConfidence <= 0 {
		cfg.SuggestConfidence = 0.6
	}
	if cfg.Now == nil {
		cfg.Now = func() time.Time { return time.Now().UTC() }
	}
	return &FAQResponder{
		generator:      cfg.Generator,
		store:          cfg.Store,
		tenantID:       cfg.TenantID,
		autoReplyFloor: cfg.AutoReplyConfidence,
		suggestFloor:   cfg.SuggestConfidence,
		now:            cfg.Now,
		logger:         logger,
		metrics:        cfg.Metrics,
	}, nil
}

// Close marks the responder closed. Implements lifecycle.Closer.
func (r *FAQResponder) Close(_ context.Context) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.closed = true
	return nil
}

// Respond runs the EC-8-2 pipeline. Decomposed into helpers so the
// orchestrator stays at cyclomatic 5 (the upper bound for the
// 10-sprint streak target).
func (r *FAQResponder) Respond(ctx context.Context, req FAQRequest) (FAQResult, error) {
	if err := r.guardRespond(req); err != nil {
		return FAQResult{}, err
	}
	candidates, err := r.retrieveCandidates(ctx, req)
	if err != nil {
		return FAQResult{}, fmt.Errorf("retrieve faq candidates: %w", err)
	}
	if len(candidates) == 0 {
		out := r.escalationResult(req, "", ErrNoFAQMatch)
		r.recordOutcome(out.Outcome)
		return out, nil
	}
	ranked := rerank(candidates, req.Text)
	top := ranked[0]
	reply, source := r.phraseReply(ctx, req, ranked)
	confidence := finalConfidence(top.score, req.Classification.Confidence)
	outcome := routeByConfidence(confidence, req.Classification.FlagForReview)
	res := FAQResult{
		MessageID:      req.MessageID,
		Outcome:        outcome,
		ReplyText:      reply,
		MatchedEntryID: top.entry.EntryID,
		Confidence:     confidence,
		PhraseSource:   source,
		RespondedAt:    r.now().UTC(),
	}
	r.recordOutcome(outcome)
	return res, nil
}

func (r *FAQResponder) guardRespond(req FAQRequest) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.closed {
		return ErrFAQResponderClosed
	}
	if strings.TrimSpace(req.MessageID) == "" {
		return fmt.Errorf("%w: message_id required", ErrFAQResponderUnconfigured)
	}
	if strings.TrimSpace(req.Text) == "" {
		return fmt.Errorf("%w: text required", ErrFAQResponderUnconfigured)
	}
	return nil
}

// retrieveCandidates pulls tenant+language+intent-scoped entries
// from the FAQ store.
func (r *FAQResponder) retrieveCandidates(ctx context.Context, req FAQRequest) ([]FAQEntry, error) {
	query := FAQSearchQuery{
		TenantID: r.tenantID,
		Language: req.Classification.Language,
		Intent:   req.Classification.Intent,
	}
	candidates, err := r.store.Search(ctx, query)
	if err != nil {
		return nil, err
	}
	// Defensive filter: even though the store is supposed to
	// enforce tenant scoping, the responder re-checks so a
	// misconfigured adapter cannot leak a row across tenants.
	filtered := make([]FAQEntry, 0, len(candidates))
	for _, e := range candidates {
		if e.TenantID == r.tenantID {
			filtered = append(filtered, e)
		}
	}
	return filtered, nil
}

// rerank returns the entries scored against the request text,
// sorted highest score first. Returns at most top 3 so the LLM
// rephrase prompt stays bounded.
func rerank(entries []FAQEntry, text string) []rankedEntry {
	scored := make([]rankedEntry, 0, len(entries))
	for _, e := range entries {
		scored = append(scored, rankedEntry{entry: e, score: scoreFAQEntry(e, text)})
	}
	sort.SliceStable(scored, func(i, j int) bool {
		if scored[i].score == scored[j].score {
			return scored[i].entry.EntryID < scored[j].entry.EntryID
		}
		return scored[i].score > scored[j].score
	})
	if len(scored) > 3 {
		scored = scored[:3]
	}
	return scored
}

// phraseReply runs the LLM rephrase pass over the top-3 matches
// and validates the response length. On any LLM failure (or
// over-budget reply) the responder falls back to the verbatim
// answer of the top match (template fallback).
func (r *FAQResponder) phraseReply(ctx context.Context, req FAQRequest, ranked []rankedEntry) (string, FAQPhraseSource) {
	if len(ranked) == 0 {
		return "", FAQPhraseSourceTemplate
	}
	system, user := buildFAQPrompt(req, ranked)
	resp, err := r.generator.Complete(ctx, port.AICompletionRequest{
		Messages: []port.AIMessage{
			{Role: "system", Content: system},
			{Role: "user", Content: user},
		},
		Temperature: floatPtr(0.3),
		MaxTokens:   intPtr(300),
	})
	if err != nil {
		r.logger.Warn("customerservice.faq.llm_unavailable", "tenant_id", r.tenantID, "message_id", req.MessageID, "error", err)
		return ranked[0].entry.Answer, FAQPhraseSourceTemplate
	}
	reply := strings.TrimSpace(resp.Content)
	if reply == "" || len(reply) > MaxFAQResponseLength {
		r.logger.Warn("customerservice.faq.llm_unusable", "tenant_id", r.tenantID, "message_id", req.MessageID, "len", len(reply))
		return ranked[0].entry.Answer, FAQPhraseSourceTemplate
	}
	return reply, FAQPhraseSourceLLM
}

// escalationResult is the deterministic shape returned when no FAQ
// matched. The MatchError is the typed ErrNoFAQMatch sentinel so
// the EC-8-3 webhook can switch on it via errors.Is.
func (r *FAQResponder) escalationResult(req FAQRequest, replyText string, sentinel error) FAQResult {
	return FAQResult{
		MessageID:    req.MessageID,
		Outcome:      FAQOutcomeEscalated,
		ReplyText:    replyText,
		MatchError:   sentinel,
		PhraseSource: FAQPhraseSourceTemplate,
		RespondedAt:  r.now().UTC(),
	}
}

func (r *FAQResponder) recordOutcome(outcome FAQOutcome) {
	if r.metrics == nil {
		return
	}
	r.metrics.RecordFAQResponse(r.tenantID, string(outcome))
}

// rankedEntry pairs an entry with its rerank score.
type rankedEntry struct {
	entry FAQEntry
	score float64
}

// scoreFAQEntry returns a [0, 1] BM25-flavoured similarity score.
// Implementation stays stdlib-only (no pgvector dependency at the
// package level) so the in-memory adapter + test fixtures work
// without spinning Postgres.
//
// Scoring components (additive, capped at 1.0):
//   - Question word overlap with text  (+0.5 max)
//   - Keyword match in text            (+0.3 max)
//   - Exact substring match            (+0.2 max)
func scoreFAQEntry(entry FAQEntry, text string) float64 {
	loweredText := strings.ToLower(text)
	score := questionOverlapScore(entry.Question, loweredText)
	score += keywordOverlapScore(entry.Keywords, loweredText)
	score += substringScore(entry.Question, loweredText)
	return clampUnit(score)
}

// questionOverlapScore awards up to 0.5 for word overlap.
func questionOverlapScore(question, lowered string) float64 {
	tokens := tokenize(strings.ToLower(question))
	if len(tokens) == 0 {
		return 0
	}
	hits := 0
	for _, tok := range tokens {
		if len(tok) < 3 {
			continue
		}
		if strings.Contains(lowered, tok) {
			hits++
		}
	}
	if hits == 0 {
		return 0
	}
	ratio := float64(hits) / float64(len(tokens))
	return 0.5 * ratio
}

// keywordOverlapScore awards up to 0.3 for keyword matches.
func keywordOverlapScore(keywords []string, lowered string) float64 {
	if len(keywords) == 0 {
		return 0
	}
	hits := 0
	for _, kw := range keywords {
		kw = strings.ToLower(strings.TrimSpace(kw))
		if kw == "" {
			continue
		}
		if strings.Contains(lowered, kw) {
			hits++
		}
	}
	if hits == 0 {
		return 0
	}
	ratio := float64(hits) / float64(len(keywords))
	return 0.3 * ratio
}

// substringScore awards 0.2 when the entire question is a substring
// of the text (or vice-versa for short questions).
func substringScore(question, lowered string) float64 {
	q := strings.ToLower(strings.TrimSpace(question))
	if q == "" {
		return 0
	}
	if strings.Contains(lowered, q) {
		return 0.2
	}
	return 0
}

// tokenize splits a string into lowercase word tokens.
func tokenize(s string) []string {
	fields := strings.FieldsFunc(s, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r >= 0x4e00 && r <= 0x9fff)
	})
	return fields
}

// finalConfidence is the confidence the auto-reply gate routes on.
// The classifier already filters by intent + language so the gate
// is driven by classifier confidence; the rerank score is used to
// pick the best entry. A near-zero rerank (no real match) is the
// only case where the responder downscales: the resulting
// classifier-adjusted score routes to escalate.
//
// Cyclomatic 3.
func finalConfidence(rerank, classifier float64) float64 {
	if rerank <= 0 {
		return 0
	}
	if rerank < weakMatchFloor {
		return classifier * weakMatchPenalty
	}
	return classifier
}

// weakMatchFloor is the rerank threshold below which the responder
// treats the FAQ match as weak and downscales the routed confidence.
const weakMatchFloor = 0.1

// weakMatchPenalty is multiplied into the classifier confidence when
// the FAQ rerank score is below weakMatchFloor.
const weakMatchPenalty = 0.5

// routeByConfidence implements the three-tier auto-reply gate.
// Pure function so reviewers can prove the gate without re-reading
// the orchestrator.
func routeByConfidence(score float64, flagForReview bool) FAQOutcome {
	if flagForReview {
		return FAQOutcomeEscalated
	}
	switch {
	case score > 0.8:
		return FAQOutcomeAutoReplied
	case score >= 0.6:
		return FAQOutcomeSuggested
	default:
		return FAQOutcomeEscalated
	}
}

// buildFAQPrompt builds the system + user prompt for the LLM
// rephrase pass over the top-3 matches.
func buildFAQPrompt(req FAQRequest, ranked []rankedEntry) (string, string) {
	system := "You are a friendly e-commerce customer service agent. " +
		"Rephrase the most relevant FAQ entry into a concise, " +
		"polite reply. Keep it under " + fmt.Sprintf("%d", MaxFAQResponseLength) + " characters. " +
		"Do not invent facts; stick to the supplied FAQ answers."
	var sb strings.Builder
	sb.WriteString("Customer message:\n")
	sb.WriteString(req.Text)
	sb.WriteString("\n\nTop FAQ matches:\n")
	for i, r := range ranked {
		fmt.Fprintf(&sb, "%d. Q: %s\n   A: %s\n", i+1, r.entry.Question, r.entry.Answer)
	}
	return system, sb.String()
}

// errFAQUnwrap allows tests to verify wrapping without constructing
// the package-internal fmt.Errorf return values.
func errFAQUnwrap(err error) error { return errors.Unwrap(err) }
