{{- if not .Values.secrets.externalSecretManager }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentic-ecommerce.fullname" . }}-secrets
  labels:
    {{- include "agentic-ecommerce.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data: {}
{{- end }}
